#!/usr/bin/env bash
# Installs Nginx with the following configurations:
## server
## Nginx should be listening on port 80
## As an answer file, write a Bash script that configures a new Ubuntu machine\
### to respect above requirements (this script will be run on the server itself)
## You can’t use systemctl for restarting nginx

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > sudo tee /var/www/html/index.html

cat << EOF > /etc/nginx/sites-available/default
server {
    listen              80 default_server;
    listen              [::]:80 default_server;

    root                /var/www/html;
    index               index.html index.htm index.nginx-debian.html;
}
EOF


sudo service nginx restart
