#!/bin/env bash

# Check if the user has root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Display headers
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

# Get listening ports using lsof
lsof -i -P -n | grep LISTEN | while read line
do
    protocol=$(echo $line | awk '{print $1}')
    local_address=$(echo $line | awk '{print $8}')
    pid=$(echo $line | awk '{print $2}')
    program=$(ps -p $pid -o comm=)

    # Print information
    echo "$protocol    -    $local_address    *    LISTEN    $pid/$program"
done
