#!/bin/env bash

# Checking for root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Defining the desired host resolutions
HOSTS_FILE="/etc/hosts"
LOCALHOST_IP="127.0.0.2"
FACEBOOK_IP="8.8.8.8"

# Add or update localhost resolution
grep -q "localhost" $HOSTS_FILE && sed -i "s/.*localhost.*/$LOCALHOST_IP localhost/" $HOSTS_FILE || echo "$LOCALHOST_IP localhost" >> $HOSTS_FILE

# Add or update facebook.com resolution
grep -q "facebook.com" $HOSTS_FILE && sed -i "s/.*facebook.com.*/$FACEBOOK_IP facebook.com/" $HOSTS_FILE || echo "$FACEBOOK_IP facebook.com" >> $HOSTS_FILE
